FROM python:3.12-slim

# Copie as dependências do host para o contêiner (main.py e requirements.txt)

COPY main.py .
COPY requirements.txt .

RUN pip install -r requirements.txt

CMD ["python3", "main.py"]
